server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 100
  servlet:
    context-path: /

mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html

logging:
  level:
    com.cy: debug

#page 自己定义的参数 经常变化的数字
db.page:
    pageSize: 5